language: bash

services:
- docker

env:
  global:
  - ALPINE_VER=3.9
  - BASE_IMAGE_STABILITY_TAG=2.3.0
  matrix:
  - ELASTICSEARCH_VER=7.2.0 TAGS=7.2,7,latest
  - ELASTICSEARCH_VER=6.8.1 TAGS=6.8,6

script:
- travis_retry make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
