language: bash

services:
- docker

env:
  global:
  - ALPINE_VER=3.9
  - BASE_IMAGE_STABILITY_TAG=2.2.2
  matrix:
  - ELASTICSEARCH_VER=6.7.2 TAGS=6.7,6,latest
  - ELASTICSEARCH_VER=5.6.16 TAGS=5.6,5

script:
- travis_retry make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
