language: bash

services:
  - docker

env:
  global:
    - ALPINE_VER=3.9
    - BASE_IMAGE_STABILITY_TAG=2.2.1
  matrix:
    - ELASTICSEARCH_VER=6.7.1 TAGS=6.7,6,latest
    - ELASTICSEARCH_VER=5.6.16 TAGS=5.6,5

script:
  - travis_retry make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"